baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
  name = "WU HAO"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by emmett Ng"
  keywords = "homepage, General Intelligence, Computational neuroscience, Category Theory, Haskell, Data Science, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

# Social icons

  [[params.social]]
    name = "email"
    url  = "mailto:wuhao29@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/emmettng"

#  [[params.social]]
#    name = "linkedin"
#    url  = "https://www.linkedin.com/in/hao-w-5a11ab58/"


[languages]
  [languages.en]
    title = "emmett Ng"
    subtitle = "yes you are"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Î»a -> "
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "mE"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "category"
        name = "Category&Haskell"
        url = "haskell/"
      [[languages.en.menu.main]]
        identifier = "blogs"
        name = "Blogs"
        url = "blogs/"
      [[languages.en.menu.main]]
        identifier = "data"
        name = "DataScience"
        url = "datascience/"
      [[languages.en.menu.main]]
        identifier = "agi"
        name = "AGI"
        url = "agi/"